src/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from web.contacts_web.views import index_view

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'test_contacts.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^contact/', include('web.contacts_web.urls', namespace='contacts')),
    url(r'^$', index_view, name='index_page'),

)

src/web/contacts_web/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.utils.translation import ugettext_lazy as _
from web.contacts_web.views import contact_details

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'test_contacts.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'(?P<pk>\d+)/$', contact_details, name='contact_page'),
)

src/core/contacts/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Contact(models.Model):
    owner = models.ForeignKey(User)
    phone = models.CharField(max_length=12, blank=True, null=True)
    home_phone = models.CharField(max_length=12, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)

    def __unicode__(self):
        return "ID: %s - Username: %s" % (self.pk, self.owner.username)

src/web/contacts_web/views/ContactDetailsView.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView
from web.contacts_web.facades.ContactsFacade import ContactsFacade


class ContactDetailsView(TemplateView):
    template_name = 'test_contacts/contact_details.html'
    contacts_facade = ContactsFacade()

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        context['contact'] = self.contacts_facade.get_user_contact(kwargs['pk'])
        return context

src/web/contacts_web/views/IndexView.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView
from web.contacts_web.facades.ContactsFacade import ContactsFacade


class IndexView(TemplateView):
    template_name = 'test_contacts/index_page.html'
    contacts_facade = ContactsFacade()

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data()
        context['users'] = self.contacts_facade.user_service.get_all()
        return context

src/web/contacts_web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ContactsProject</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
{#            <li><a href="{% url 'index_page' %}">Contacts List</a></li>#}
{#            </li>#}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
<div class="container main_container">
{% block page_content %}
{% endblock %}
</div>
</body>
</html>

src/web/contacts_web/templates/test_contacts/contact_details.html
{% extends 'base.html' %}

{% block page_content %}
    <a class="btn btn-success" href="{% url 'index_page' %}">Назад к списку</a>
    {% if contact %}
        <h3>{{ contact.owner.username }}</h3>
        <dl class="dl-horizontal">
            <dt>Номер телефона:</dt>
            <dd>{{ contact.phone }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Электронная почта:</dt>
            <dd>{{ contact.email }}</dd>
        </dl>
    {% else %}
        <h3>Нет данных</h3>
    {% endif %}
{% endblock %}

src/web/contacts_web/templates/test_contacts/index_page.html
{% extends 'base.html' %}
{% block page_content %}
    <h3>Список пользователей:</h3>
    <ol>
        {% for user in users %}
            <li>
                <a href="{% url 'contacts:contact_page' user.id %}">
                    {{ user.username }}
                </a>
            </li>
        {% endfor %}
    </ol>
{% endblock %}